-- MySQL Script generated by MySQL Workbench
-- Sat Jul 13 22:11:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema byhvchma1fkwfhn1iyj7
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema byhvchma1fkwfhn1iyj7
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `byhvchma1fkwfhn1iyj7` DEFAULT CHARACTER SET utf8 ;
USE `byhvchma1fkwfhn1iyj7` ;

-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_usuarios_plataforma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_usuarios_plataforma` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_usuarios_plataforma` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `perfil` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_servicios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_servicios` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_servicios` (
  `id_servicio` INT NOT NULL AUTO_INCREMENT,
  `descripcion_servicio` VARCHAR(150) NOT NULL,
  `costo_unitario` DECIMAL(5,2) NULL,
  `validar_pesaje` TINYINT NULL,
  PRIMARY KEY (`id_servicio`),
  UNIQUE INDEX `descripcion_servicio_UNIQUE` (`descripcion_servicio` ASC) INVISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_material` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_material` (
  `id_material` INT NOT NULL AUTO_INCREMENT,
  `descripcion_material` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_material`),
  UNIQUE INDEX `descripcion_material_UNIQUE` (`descripcion_material` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_recomendacion_lavado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_recomendacion_lavado` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_recomendacion_lavado` (
  `id_recomendacion` INT NOT NULL AUTO_INCREMENT,
  `fk_id_material` INT NOT NULL,
  `fk_id_servicio` INT NOT NULL,
  PRIMARY KEY (`id_recomendacion`),
  INDEX `fk_id_material_idx` (`fk_id_material` ASC) VISIBLE,
  INDEX `fk_id_servicio_idx` (`fk_id_servicio` ASC) VISIBLE,
  CONSTRAINT `fk_id_material_reco`
    FOREIGN KEY (`fk_id_material`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_material` (`id_material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_servicio_reco`
    FOREIGN KEY (`fk_id_servicio`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_servicios` (`id_servicio`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_tipo_descuentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_tipo_descuentos` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_tipo_descuentos` (
  `id_tipo_descuento` INT NOT NULL AUTO_INCREMENT,
  `tipo_descuento_desc` VARCHAR(100) NOT NULL,
  `cantidad_descuento` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`id_tipo_descuento`),
  UNIQUE INDEX `tipo_descuento_desc_UNIQUE` (`tipo_descuento_desc` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_clientes_registrados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_clientes_registrados` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_clientes_registrados` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `identificacion_cliente` VARCHAR(13) NOT NULL,
  `tipo_identificacion_cliente` VARCHAR(100) NOT NULL,
  `nombre_cliente` VARCHAR(100) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `telefono_cliente` VARCHAR(10) NOT NULL,
  `correo_cliente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `identificacion_cliente_UNIQUE` (`identificacion_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_pedido` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_pedido` (
  `id_pedido_cabecera` INT NOT NULL AUTO_INCREMENT,
  `fecha_pedido` VARCHAR(45) NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  `telefono_cliente` VARCHAR(10) NOT NULL,
  `correo_cliente` VARCHAR(100) NULL,
  `fk_id_descuentos` INT NULL,
  `pedido_subtotal` DECIMAL(4,2) NOT NULL,
  `cantidad_articulos` INT NOT NULL,
  `fk_id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_pedido_cabecera`),
  INDEX `fk_id_usuario_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_id_descuentos_idx` (`fk_id_descuentos` ASC) VISIBLE,
  INDEX `fk_id_cliente_pedido_idx` (`fk_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_id_usuario_pedido`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_usuarios_plataforma` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_descuentos_pedido`
    FOREIGN KEY (`fk_id_descuentos`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_tipo_descuentos` (`id_tipo_descuento`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_id_cliente_pedido`
    FOREIGN KEY (`fk_id_cliente`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_clientes_registrados` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_pedido_detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_pedido_detalle` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_pedido_detalle` (
  `id_pedido_detalle` INT NOT NULL AUTO_INCREMENT,
  `fk_id_servicio` INT NOT NULL,
  `libras` DECIMAL(2,2) NULL,
  `precio_servicio` DECIMAL(4,2) NOT NULL,
  `fk_id_pedido` INT NOT NULL,
  PRIMARY KEY (`id_pedido_detalle`),
  INDEX `fk_id_servicio_idx` (`fk_id_servicio` ASC) VISIBLE,
  INDEX `fk_id_pedido_idx` (`fk_id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_id_servicio_detalle`
    FOREIGN KEY (`fk_id_servicio`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_servicios` (`id_servicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_pedido_detalle`
    FOREIGN KEY (`fk_id_pedido`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_pedido` (`id_pedido_cabecera`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_estados` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `descripcion_estado` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `byhvchma1fkwfhn1iyj7`.`tb_asignaciones_empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `byhvchma1fkwfhn1iyj7`.`tb_asignaciones_empleado` ;

CREATE TABLE IF NOT EXISTS `byhvchma1fkwfhn1iyj7`.`tb_asignaciones_empleado` (
  `id_asignaciones` INT NOT NULL AUTO_INCREMENT,
  `fk_id_usuario` INT NOT NULL,
  `fecha_asignacion` DATE NOT NULL,
  `fk_id_pedido` INT NOT NULL,
  `fk_id_estado` INT NULL,
  PRIMARY KEY (`id_asignaciones`),
  INDEX `fk_id_usuario_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_id_pedido_idx` (`fk_id_pedido` ASC) VISIBLE,
  INDEX `fk_id_estado_idx` (`fk_id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_id_usuario_asig`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_usuarios_plataforma` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_pedido_asig`
    FOREIGN KEY (`fk_id_pedido`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_pedido` (`id_pedido_cabecera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_estado_asig`
    FOREIGN KEY (`fk_id_estado`)
    REFERENCES `byhvchma1fkwfhn1iyj7`.`tb_estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
